import { Case, Evidence, CustodyLog, User, DashboardStats } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Admin',
    email: 'admin@evidence.sys',
    role: 'Admin',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Sarah Investigator',
    email: 'sarah@evidence.sys',
    role: 'Investigator',
    createdAt: '2024-01-16T10:00:00Z',
  },
  {
    id: '3',
    name: 'Mike Reviewer',
    email: 'mike@evidence.sys',
    role: 'Reviewer',
    createdAt: '2024-01-17T10:00:00Z',
  },
];

export const mockCases: Case[] = [
  {
    id: '1',
    caseId: 'CASE-2026-004',
    title: 'Arm Robery',
    description: '',
    location: 'Lacuna',
    investigatorName: 'Opeyemi',
    createdBy: '2',
    createdAt: '2026-02-11T09:00:00Z',
    status: 'Open',
    priority: 'Medium',
    evidenceCount: 0,
  },
  {
    id: '2',
    caseId: 'CASE-2024-001',
    title: 'Data Breach Investigation - Acme Corp',
    description: 'Investigation into unauthorized access to customer database. Suspected insider threat with possible external collaboration.',
    investigatorName: 'Sarah Chen',
    createdBy: '2',
    createdAt: '2026-02-11T14:30:00Z',
    status: 'In Progress',
    priority: 'Critical',
    evidenceCount: 3,
  },
  {
    id: '3',
    caseId: 'CASE-2024-002',
    title: 'Ransomware Attack Analysis',
    description: 'Forensic analysis of ransomware deployment across multiple workstations. Focus on identifying entry point and lateral movement.',
    investigatorName: 'Michael Torres',
    createdBy: '3',
    createdAt: '2026-02-11T08:00:00Z',
    status: 'Open',
    priority: 'High',
    evidenceCount: 2,
  },
  {
    id: '4',
    caseId: 'CASE-2024-003',
    title: 'Financial Fraud Digital Evidence',
    description: 'Collection and analysis of digital evidence related to suspected wire fraud scheme.',
    investigatorName: 'Emily Watson',
    createdBy: '1',
    createdAt: '2026-02-11T10:00:00Z',
    status: 'Under Review',
    priority: 'Medium',
    evidenceCount: 5,
  },
];

export const mockEvidence: Evidence[] = [
  {
    id: '1',
    evidenceId: 'EVD-2024-001',
    caseId: '1',
    filename: 'server_logs_2024-02-01.log',
    fileType: 'Log',
    sourceDevice: 'Web Server - 192.168.1.100',
    sha256Hash: 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2',
    md5Hash: '5d41402abc4b2a76b9719d911017c592',
    size: 2048576,
    capturedAt: '2024-02-01T09:30:00Z',
    uploadedBy: '2',
    notes: 'Server access logs showing unauthorized login attempts',
    verified: true,
    lastVerifiedAt: '2024-02-10T15:00:00Z',
  },
  {
    id: '2',
    evidenceId: 'EVD-2024-002',
    caseId: '1',
    filename: 'database_dump.sql',
    fileType: 'Document',
    sourceDevice: 'Database Server - 192.168.1.50',
    sha256Hash: 'b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3',
    size: 15728640,
    capturedAt: '2024-02-01T10:00:00Z',
    uploadedBy: '2',
    notes: 'Database snapshot at time of incident',
    verified: true,
    lastVerifiedAt: '2024-02-10T15:05:00Z',
  },
  {
    id: '3',
    evidenceId: 'EVD-2024-003',
    caseId: '2',
    filename: 'phishing_email.eml',
    fileType: 'Document',
    sourceDevice: 'Email Server',
    sha256Hash: 'c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4',
    size: 45056,
    capturedAt: '2024-02-05T15:00:00Z',
    uploadedBy: '2',
    notes: 'Original phishing email with headers',
    verified: false,
  },
];

export const mockCustodyLogs: CustodyLog[] = [
  {
    id: '1',
    evidenceId: '1',
    action: 'Collected',
    performedBy: 'sarah.chen@forensics.com',
    performedTo: 'Data Center - Rack 14',
    purpose: 'Initial evidence collection from production server',
    timestamp: '2024-01-15T10:30:00Z',
    logHash: 'log1hash',
  },
  {
    id: '2',
    evidenceId: '1',
    action: 'Transferred',
    performedBy: 'sarah.chen@forensics.com',
    performedTo: 'michael.torres@forensics.com',
    purpose: 'Transfer for log analysis',
    timestamp: '2024-01-15T15:00:00Z',
    prevLogHash: 'log1hash',
    logHash: 'log2hash',
  },
  {
    id: '3',
    evidenceId: '1',
    action: 'Analyzed',
    performedBy: 'michael.torres@forensics.com',
    performedTo: 'Forensic Lab - Room 201',
    purpose: 'Timeline analysis of authentication events',
    timestamp: '2024-01-16T11:00:00Z',
    prevLogHash: 'log2hash',
    logHash: 'log3hash',
  },
  {
    id: '4',
    evidenceId: '1',
    action: 'Collected',
    performedBy: 'sarah.chen@forensics.com',
    performedTo: 'Office Building - Floor 3',
    purpose: 'Live memory acquisition from suspect workstation',
    timestamp: '2024-01-15T12:45:00Z',
    prevLogHash: 'log3hash',
    logHash: 'log4hash',
  },
  {
    id: '5',
    evidenceId: '2',
    action: 'Collected',
    performedBy: 'sarah.chen@forensics.com',
    performedTo: 'Data Center - Rack 14',
    purpose: 'Database snapshot at time of incident',
    timestamp: '2024-02-01T10:00:00Z',
    logHash: 'log5hash',
  },
  {
    id: '6',
    evidenceId: '2',
    action: 'Transferred',
    performedBy: 'sarah.chen@forensics.com',
    performedTo: 'michael.torres@forensics.com',
    purpose: 'Transfer for database analysis',
    timestamp: '2024-02-05T10:00:00Z',
    prevLogHash: 'log5hash',
    logHash: 'log6hash',
  },
  {
    id: '7',
    evidenceId: '2',
    action: 'Analyzed',
    performedBy: 'michael.torres@forensics.com',
    performedTo: 'Forensic Lab - Room 201',
    purpose: 'Database forensic analysis completed',
    timestamp: '2024-02-08T14:30:00Z',
    prevLogHash: 'log6hash',
    logHash: 'log7hash',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalCases: 45,
  activeCases: 12,
  totalEvidence: 234,
  verifications: 156,
  recentVerifications: 18,
  pendingReviews: 5,
};
